### ISSUE TITLE
Color is saved to saved teams array when it shouldn't be

### ISSUE THREAD

**Issue by bainer125** [bainer125/yagos#4]
When a custom color is picked for a team, it is saved in the "teams" array that saves all of the preset team information. This is not ideal behavior, but most importantly, I have no idea where this assignment happens. This is related to latest commit on big-cleanup branch

**Comment by zschaller27** [comment]
Non-issue, there isn't any change to teams array when changing colours. The issue is that the teams aren't requerried when the user changes to a new team.
